require("user.settings")
require("user.keymaps")
require("user.packer")

require("user.plugins.nord")
require("user.plugins.nvim-tree")
require("user.plugins.lualine")
require("user.plugins.treesitter")
require("user.plugins.indent-blankline")
require("user.plugins.autopairs")
require("user.plugins.bufferline")
require("user.plugins.toggleterm")
require("user.plugins.telescope")

require("user.lsp")
